### PR TITLE
Ensure Git operations do not fail unnecessarily

### LINKED ISSUE #27: Git operations fail when the .parlance.json file cannot be read
When Parlance is presented with an invalid .parlance.json, the frontend does not show an option to go to the VCS operations.

Even if you navigate to the VCS URL manually, attempting to issue a VCS command results in a 500 from the server.

### PR DESCRIPTION
**Pull request by vicr123**
Currently, Git operations fail if the .parlance.json file cannot be read properly. This PR refactors the Git support to ensure that it is resilient against errors in the .parlance.json file.

Closes #27

### CODE REVIEW

File: Parlance/Controllers/ProjectVcsController.cs [hunk 1]
```diff
@@ -77,11 +75,19 @@ public async Task<IActionResult> PullFromVcs(string project)
...
+            await _versionControlService.ReconcileRemoteWithLocal(p);
+
+            try
+            {
+                var proj = p.GetParlanceProject();
+                await _indexingService.IndexProject(proj);
+            }
+            catch (ParlanceJsonFileParseException)
+            {
+                // ignored
```
Comment (reflectronic) [inline Parlance/Controllers/ProjectVcsController.cs:89]: It's OK to ignore these because trying to actually access the subprojects will error out anyway?

**Review by reflectronic — APPROVED** [review]

File: Parlance/Controllers/ProjectVcsController.cs (hunk 1 above)
Comment (vicr123) [reply Parlance/Controllers/ProjectVcsController.cs:89]: Indexation can't be performed because the data about where the translation files are is not available, and there's not really anywhere to report it to.

Eventually someone will notice when they try to look at the project
